# Generated by Django 4.0.5 on 2022-06-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0002_remove_post_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likesPost',
            field=models.IntegerField(null=True),
        ),
    ]
